app-sre/unleash

.gitmodules, Dockerfile, README.md, index.js, lib/index.js, lib/profile.js, lib/strategy.js, openshift/unleash.yaml, package.json
Still missing:
- OAuth Github to validate org/team.
- Fix exception when user has no public github email.
- make check
- make build/deploy
=> Initial Auth configuration

README.md, index.js, openshift/unleash.yaml
=> Enabling multi-tenancy settings

openshift/unleash.yaml
=> Fix template vars

openshift/unleash.yaml
=> Fix openshift app name

openshift/unleash.yaml
=> Default values for new parameters

openshift/unleash.yaml
=> Secrets cannot be path

index.js, lib/strategy.js
=> Validating the Team in addition to the Org

README.md, index.js, openshift/unleash.yaml
=> Removing DB creation logic

openshift/unleash.yaml
=> Fix secret name for DATABASE_HOST

openshift/unleash.yaml
=> Split config secret from identifier

openshift/unleash.yaml
=> Split tokenSecret from config

Dockerfile, README.md, openshift/unleash.yaml, package.json
1. fix apiVersion for Deployment
2. build from an image from quay.io
3. unleash-server@3.6.1 require node 12
Signed-off-by: Feng Huang <fehuang@redhat.com>
=> fix templatea and dockerfile 

Dockerfile
Signed-off-by: Feng Huang <fehuang@redhat.com>
=> build based on ubi

.gitignore, lib/strategy.js
Signed-off-by: Feng Huang <fehuang@redhat.com>
=> get all teams pages

openshift/unleash.yaml
This change will enable service scaledown by setting REPLICAS to 0
Part of https://issues.redhat.com/browse/APPSRE-4544
Signed-off-by: Gerd Oberlechner <goberlec@redhat.com>
=> add REPLICAS parameter to saas template

package.json
=> upgrade unleash-server to 4.8.2

Dockerfile
=> upgrade to node-14

index.js
upgrading from 3 to 4 updates auth method: https://docs.getunleash.io/deploy/configuring_unleash#further-customization
=> update auth method

index.js
=> restore preRouterHook

index.js
```
500 TypeError: Id is required
at new User (/opt/app-root/src/node_modules/unleash-server/dist/lib/types/user.js:12:19)
at Strategy._verify (/opt/app-root/src/index.js:80:11)
at /opt/app-root/src/node_modules/passport-oauth2/lib/strategy.js:205:24
at /opt/app-root/src/lib/strategy.js:182:15
at passBackControl (/opt/app-root/src/node_modules/oauth/lib/oauth2.js:134:9)
at IncomingMessage.<anonymous> (/opt/app-root/src/node_modules/oauth/lib/oauth2.js:157:7)
at IncomingMessage.emit (events.js:412:35)
at endReadableNT (internal/streams/readable.js:1334:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
https://github.com/Unleash/unleash/blob/03dc579cfa54691d8885822914544fceda02c183/src/lib/types/user.ts#L61
=> unleash User id

index.js
following https://github.com/Unleash/unleash-examples/tree/main/v4/securing-google-auth
=> loginUserWithoutPassword

openshift/unleash.yaml
This work is to clear the DVO alerts for unleash. Part of [APPSRE-5015](https://issues.redhat.com/browse/APPSRE-5015), [APPSRE-5016](https://issues.redhat.com/browse/APPSRE-5016), [APPSRE-5341](https://issues.redhat.com/browse/APPSRE-5341), and [APPSRE-5350](https://issues.redhat.com/browse/APPSRE-5350)
=> Add readiness and liveness probes

openshift/unleash.yaml
This work is to clear the DVO alerts. Part of [APPSRE-5337](https://issues.redhat.com/browse/APPSRE-5337) and [APPSRE-4942](https://issues.redhat.com/browse/APPSRE-4942)
=> create service account for unleash

openshift/unleash.yaml
Follow up to this [PR](https://github.com/app-sre/unleash/pull/32).
=> fixing indentation for affinity

openshift/unleash.yaml
=> set UNLEASH_URL and manage openshift route

dashboards/grafana-dashboard-unleash.configmap.yaml
Part of [APPSRE-4895](https://issues.redhat.com/browse/APPSRE-4895)
=> adding grafana dashboard for unleash

dashboards/grafana-dashboard-unleash.configmap.yaml
Follow up to [39](https://github.com/app-sre/unleash/pull/39)
=> editing configmap for unleash

dashboards/grafana-dashboard-unleash.configmap.yaml
Follow up to [39](https://github.com/app-sre/unleash/pull/39) and [40](https://github.com/app-sre/unleash/pull/40)
=> change from yaml to json for grafana dashboard

index.js
Fix syntax bug from: https://github.com/app-sre/unleash/pull/43
=> [APPSRE-7594] drop BEARER requirement from authorization header: fix "or check"

README.md
Update examples to match the [Unleash Python SDK docs](https://docs.getunleash.io/reference/sdks/python) and [README](https://github.com/Unleash/unleash-client-python#usage).
Depends on #43.
=> Update README for Unleash 4

openshift/unleash.yaml
Part of [APPSRE-8174](https://issues.redhat.com/browse/APPSRE-8174), unset cpu limits to avoid cpu throttle.
=> Unset cpu limits

openshift/unleash.yaml
=> fix annotations indentation

.gitignore, build_deploy.sh, pko/demo-package.yaml, pko/package/manifest.yaml, pko/package/unleash.yaml.gotmpl, pko/validation_config.yaml, pr_check.sh
introduces PKO package bundling and publishing for unleash
part of https://issues.redhat.com/browse/APPSRE-8134
=> PKO bundling for unleash

.dockerignore, .gitleaks.toml, README.md, docker-compose.yml, keycloak_data/unleash-realm.json, keycloak_data/unleash-users-0.json
To improve dev experience for local development and test, add `docker-compose` with all dependencies & data populated.
Test:
```
$ docker-compose up --build
```
Then visit http://localhost:4242
Login with admin, username: `unleash-admin`, password: `unleash`.
All data committed are exported from local, no real secrets used.
[APPSRE-8140](https://issues.redhat.com/browse/APPSRE-8140)
=> Setup docker-compose and test data for local development

pko/demo-package.yaml, pko/package/manifest.yaml, pko/package/predeploy.yaml.gotmpl, pko/package/unleash.yaml.gotmpl, pko/validation_config.yaml
Adding predeploy step
Updating deploy step, changing to three different secrets
=> Refactor PKO

package-lock.json, package.json
Remove unused packages and bump current used packages to latest version.
=> Update and clear dependencies

package-lock.json, package.json
Bump a few dependencies, the main package `unleash-server` upgraded to `5.11.3`.
=> Upgrade unleash 5.11.3

openshift/unleash-edge.yaml
Openshift template for an [unleash-edge](https://github.com/Unleash/unleash-edge) deployment.
Ticket: [SDE-3868](https://issues.redhat.com/browse/SDE-3868)
=>  unleash-edge deployment

openshift/unleash-edge.yaml
=>  unleash-edge: add missing template var

openshift/unleash-edge.yaml
`unleash-edge` image needs a pull secret.
=>  unleash-edge: use image pull secret

openshift/unleash-edge.yaml
Fix `unleash-edge` path and startup arguments
=>  unleash-edge: fix deployment

.tekton/unleash-master-pull-request.yaml, .tekton/unleash-master-push.yaml
[APPSRE-11226](https://issues.redhat.com/browse/APPSRE-11226)
Add Tekton definitions for Unleash.
=> Add unleash tekton definitions

renovate.json
[APPSRE-11226](https://issues.redhat.com/browse/APPSRE-11226)
Add renovate.json using AppSRE best practices.
=> add renovate.json file

openshift/unleash-edge.yaml
Changed the path in the Dockerfile: https://github.com/Unleash/unleash-edge/blob/main/Dockerfile#L122
=> Fix path probes unleash edge
